# Application Name
spring.application.name=spring5-recipe-app

# DataSource Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# suppress inspection "SpringBootApplicationProperties"
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Initialization
# suppress inspection "SpringBootApplicationProperties"
spring.sql.init.mode=always
# suppress inspection "SpringBootApplicationProperties"
spring.sql.init.data-locations=classpath:data.sql

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.guru.springframework=debug

# Server Port (Optional, uncomment to change)
# server.port=8084

